module.exports = {
  apps: [
    {
      name: "safe-ai-session-backend",
      script: "dist/src/cluster.js",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        CLUSTER_ENABLED: "true",
        CLUSTER_WORKERS: "2",
      },
      exp_backoff_restart_delay: 100,
      kill_timeout: 5000,
      listen_timeout: 8000,
    },
    {
      name: "flow-keeper",
      cwd: "./keeper",
      script: "../node_modules/.bin/tsx",
      args: "index.ts",
      interpreter: "none",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "1G",
      env: {
        NODE_ENV: "production",
        ROTATION_INTERVAL_MS: "120000",
      },
      exp_backoff_restart_delay: 100,
      kill_timeout: 8000,
      listen_timeout: 10000,
    },
    {
      name: "vidgen-landing",
      cwd: "./landing",
      script: ".next/standalone/server.js",
      instances: 1,
      exec_mode: "fork",
      max_memory_restart: "512M",
      env: {
        NODE_ENV: "production",
        HOSTNAME: "127.0.0.1",
        PORT: "3001",
      },
      exp_backoff_restart_delay: 100,
      kill_timeout: 5000,
      listen_timeout: 8000,
    },
  ],
};
