bind 127.0.0.1
port 6379
protected-mode yes
timeout 0
tcp-keepalive 300
databases 4
save ""
appendonly no
maxmemory 384mb
maxmemory-policy allkeys-lru
lazyfree-lazy-eviction yes
lazyfree-lazy-expire yes
io-threads 1
hz 10
